Initial toggleFit
Davejkane/riv pull request #37
Opened 2019-05-11 04:14 UTC by gurgalex

issing features

    Initial state calculation for actual_size on image load

Broken features

    Images are not exactly being centered still.

2019-05-14 17:43 UTC, gurgalex commented
Not sure what rustfmt is finding wrong about on Travis.
Locally, I get nothing.

https://i.imgur.com/8zjgUwI.png

2019-05-14 20:11 UTC, Davejkane reviewed
I've added a couple of comments looking for some clarification on the explicit type annotations.

The z key just now only toggles between actual size and fitted for images that are larger than the screen. On smaller images, z doesn't do anything. ~I think it should scale up small images as well.~(See below) 

I'm also not sure that we need to copy only a portion of the src to the destination. I think if we just position the rectangle correctly, SDL takes care of the rest efficiently. i.e. the x and y dimensions of the dst rectangle would be negative for large images. Would probably also mean computing the centre of the rectangle would be unnecessary. x would be `(dst_width - src_width) / 2`. Likewise for y `(dst_height - src_height) / 2`. On the other hand, the way you're doing it clearly works.

2019-05-14 20:11 UTC, Davejkane commented on src/program/render.rs
> +        let texture: Texture = match self
What do all these explicit type annotations do?

2019-05-14 20:11 UTC, Davejkane commented on src/program/render.rs
> +        src_bigger
can we just compress these two lines to:
`src_dims.x > dest_dims.x || src_dims.y > dest_dims.y`
I think it's clear enough.

2019-05-14 20:18 UTC, gurgalex commented on src/program/render.rs
> +        let texture: Texture = match self
Without them, IntelliJ couldn't infer that the type was `&Texture`

https://i.imgur.com/yqhs4rz.png

2019-05-14 20:24 UTC, gurgalex commented on src/program/render.rs
> +        src_bigger
Okay

2019-05-14 20:27 UTC, Davejkane commented on src/program/render.rs
> +        let texture: Texture = match self
Hmm. Ok, I don't want to dog on your editor, but vscode seems to figure that out, which is surprising, I thought they both used the RLS underneath. I'm not a big fan of type annotations unless they're required for compilation. But you make a judgement call on this one.

2019-05-14 20:29 UTC, gurgalex commented on src/program/render.rs
> +        let texture: Texture = match self
Hmm, alright. I'll remove them as the variable names are clear enough about what is expected. Plus, thanks for the editor suggestion.

2019-05-14 20:38 UTC, Davejkane commented on src/program/render.rs
> +        let texture: Texture = match self
I'm kind of reluctantly using vscode myself. I use emacs for everything else, but for Rust, vscode really is at the front of the pack.

2019-05-14 20:49 UTC, Davejkane requested changes
You know what, I just opened a couple of images in my web browser. For ones larger than the screen I can toggle between actual size and fit-to-screen, but for smaller ones, I can't. So I think this implementation is a pretty good default behaviour.  But just like a web browser, can you try implementing this for a left mouse click as well? (remember the README and the help text).

2019-05-14 20:52 UTC, gurgalex commented
I was just going to post this as a possible reason for not wanting zoom to fill screen (blurred images for tiny pixel art)

https://i.imgur.com/bgpPxWV.png

2019-05-14 20:53 UTC, gurgalex commented
Can always be a config option though for later (user prefs)

2019-05-14 20:55 UTC, gurgalex commented
Sure, Left mouse click will toggle between actual and scale to fit on screen.

2019-05-14 21:01 UTC, Davejkane commented
Should probably be on mouse button up event (rather than mouse button down)

2019-05-14 21:27 UTC, gurgalex commented
okay, left mouse click is added for `actual_fit` toggle.

2019-05-14 21:47 UTC, gurgalex commented
>I'm also not sure that we need to copy only a portion of the src to the destination. I think if we just position the rectangle correctly, SDL takes care of the rest efficiently. i.e. the x and y dimensions of the dst rectangle would be negative for large images. Would probably also mean computing the centre of the rectangle would be unnecessary. x would be (dst_width - src_width) / 2. Likewise for y (dst_height - src_height) / 2. On the other hand, the way you're doing it clearly works.

I'll look into getting the other way working. 

Seems the way you proposed is a more common way.
I need a way that works with offsets, which I believe both can.

https://i.stack.imgur.com/6vCd6.gif

http://lazyfoo.net/tutorials/SDL/30_scrolling/index.php

2019-05-15 08:43 UTC, Davejkane commented
@gurgalex, is this ready for merging or are you still planning to change the implementation to not clip the source rectangle?

2019-05-15 08:58 UTC, gurgalex commented
It's ready for merging.

2019-05-15 09:17 UTC, Davejkane approved these changes
Cool. Now it's up to you which of your PRs you want to merge first, and which one you want to deal with merge conflicts. I'm sure there won't be much.

2019-05-15 10:45 UTC, merged