Implement dot operator
Davejkane/riv pull request #55
Opened 2019-05-16 10:01 UTC by Davejkane

This closes [#52](https://github.com/Davejkane/riv/issues/52).
* Add the last action to ui state
* Processes the period key
* process all actions returned from keyhandling and clone into last_action and return the action.

2019-05-16 10:48 UTC, gurgalex reviewed
Looks fine

2019-05-16 10:48 UTC, gurgalex commented on src/ui.rs
> +            Action::Quit | Action::ToggleFullscreen | Action::ReRender => {
I assume `ToggleFullscreen` is here because it needs to rerender the screen?

2019-05-16 11:04 UTC, gurgalex commented
Sorry about the merge conflict from #54

2019-05-16 11:13 UTC, gurgalex requested changes
Great!

Could you exempt `reRendering` from being or resetting `last_state`?

That way `ToggleFullscreen` can be switched between with `.` as well.

2019-05-16 11:15 UTC, gurgalex approved these changes

2019-05-16 11:23 UTC, gurgalex commented
My solution may have been hacky. `ReRender is never set as `last_action`.

```rust
        match a {
            Action::Quit => {
                self.last_action = Action::Noop;
                a
            }
            Action::ReRender => a,
            _ => {
                self.last_action = a.clone();
                a
            }
        }

```

2019-05-16 11:30 UTC, Davejkane commented
I'm not sure I understand. Are you suggesting that I do what you posted in that last code sample? What does that change?

2019-05-16 18:04 UTC, gurgalex commented
On fullscreen switch multiple events which emit `ReRender` can be fired as well.
`Resized`, `SizeChanged`, `Moved`, `exposed`

So, the last action is set to 

`ToggleFullscreen` and then `Noop` immediately after.

Special casing Rerender preserves any action prior to the action `ReRender`.

2019-05-17 08:45 UTC, gurgalex commented
Primary internet access is out in my area. So can you merge this?

On Thu, May 16, 2019, 06:30 Davejkane <notifications@github.com> wrote:

> I'm not sure I understand. Are you suggesting that I do what you posted in
> that last code sample? What does that change?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Davejkane/riv/pull/55?email_source=notifications&email_token=AG5ANRAAJYPDRH2T7NBVEOTPVVAW7A5CNFSM4HNK5URKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVRQUWA#issuecomment-493029976>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AG5ANRGBM4TPWA5OMTQZNILPVVAW7ANCNFSM4HNK5URA>
> .
>

2019-05-17 12:38 UTC, merged