[WIP] Glob with progress
Davejkane/riv pull request #95
Opened 2019-06-13 04:43 UTC by gurgalex

This PR aims to resolve #89 

Getting progress indications from a long-running glob wasn't that complex. Showing the progress at first launch is where the need for restructuring seems to have come from.

The major roadblock I've encountered is the need to have all images loaded before the `Program` struct can be fully constructed.

This is a problem, since to indicate progress, I need to render to the screen. However, all the screen rendering methods (specifically relating to the infobar) are on `Program`.

# workarounds or solutions

The following remedies may overlap to fix this problem.

1. Start out with no images (empty vec), and switch to a loading screen Mode. Then switch to Normal mode once first batch of images is loaded.

2. Move some of the rendering methods to the `screen` struct.
* Specialize some of the infobars to take ui_state as and argument, and others not (like loading mode)

2019-06-15 05:14 UTC, gurgalex commented
@Davejkane 

I made rendering the infobar not care about the mode it is in. Mode seemed to be used as a sort of theme for the infobar, so I gave it the proper argument name in the infobar method.

Infobar is now on the Screen struct, as I needed to render to the infobar before the program struct could be created. Specifically while in `Program::init`

It still seems like having a Loading mode could work. That could be beneficial in being able to cancel a long-running folder scan.

however, the complication in switching from Command -> Loading -> Command is what led me to this possibly hacky solution.

2019-06-17 09:59 UTC, Davejkane requested changes
This doesn't seem to work. I tried `riv "**/*"` from my home directory and the window doesn't build until all the paths are loaded, so I never get to see any progress even although it takes 15-20 seconds to load the ~50,000 images.

2019-06-17 14:05 UTC, gurgalex commented
You're right, it doesn't work in Mac OS with the current setup. Strange. Wonder why present is not showing the window. I'll look into that because some print statements say the image scanning is working incrementally.

Here's screenshots of the progress indicator.

![Screenshot from 2019-06-17 08-03-40](https://user-images.githubusercontent.com/28968644/59606490-e7ed4b00-90d6-11e9-9835-4aec9d6c9fab.png)
![Screenshot from 2019-06-17 08-03-33](https://user-images.githubusercontent.com/28968644/59606491-e7ed4b00-90d6-11e9-9de8-46b94cfbe972.png)

2019-06-17 14:09 UTC, gurgalex commented
Weird, seems I'll need to poll for events before the window will show up.
https://stackoverflow.com/questions/37848065/sdl-window-not-showing-up-at-all?rq=1

2019-06-17 20:14 UTC, Davejkane commented
@gurgalex yeah I was wondering if it was OS specific. Good luck, sounds a little tricky.

2019-06-18 20:30 UTC, gurgalex commented
@Davejkane 
I got the window to popup on Mac OS.

Slight issue you may see is a black background when the scanning is in progress. 
Seems to not happen all the time though.

I need to rework the max viewable images functionality, so that the glob only ever collects that many images.
Currently, it says it matched `100000` images when the user only asked for say `5`. The UI will then show `1 of 5` images like it should though.

2019-06-19 03:47 UTC, gurgalex commented
Now, the only thing left is to replace setting an artificial length with physically truncating the images vector.

2019-06-19 05:56 UTC, gurgalex commented
@Davejkane 
Ready for review again.

2019-06-19 16:54 UTC, Davejkane requested changes
@gurgalex Still not working for me I'm afraid. I get the spinning rainbow wheel of death until eventually the window builds with all images loaded.

2019-06-19 17:10 UTC, gurgalex commented
Alright, It's definitely Mac specific then.
Windows and Linux are tested as working.

I'll report back later today.

2019-06-19 18:44 UTC, gurgalex commented
@Davejkane 
I added a delay after consuming an event to give the window some time to draw.
I also strangely needed to allow a for loop that doesn't loop for the window to appear.

 I'm unsure if the 100ms delay is enough.

An issue now is that the rainbow spinner appears while the window is present, because the window isn't responding to any events. May be an issue, but the scanning is taking place with UI feedback.

2019-06-19 18:45 UTC, gurgalex commented
![Screen Shot 2019-06-19 at 11 43 23 AM 1](https://user-images.githubusercontent.com/28968644/59791806-bc5d9280-9287-11e9-8da5-720a3c71e745.png)

2019-06-19 18:51 UTC, gurgalex commented
It does seem the ideal solution is to keep the event loop always handling events regardless of what processing we are doing (another thread).

2019-06-20 11:12 UTC, Davejkane commented
@gurgalex just ping me when you're ready for me to have another look.

2019-06-20 15:01 UTC, gurgalex commented
@Davejkane 
Ready for another look

2019-06-21 07:41 UTC, Davejkane commented
@gurgalex It's definitely looking better. The window builds and I get the progress bar. Weird thing is the back ground keeps switching between black and the grey colour we set as the default background colour. Any idea why that would be?

2019-06-21 12:58 UTC, gurgalex commented
@Davejkane 
Not sure why it's switching background colors. 
I tried to fix that, by clearing the screen with a gray background,but still the black screen shows.

I'll look into it more this weekend.

2019-06-22 18:56 UTC, Davejkane commented
I really appreciate the effort man, I know this issue isn't easy.

2019-06-24 22:24 UTC, gurgalex commented
Let's see,
New plan for this week.

Make updating state not block getting OS events.

For each frame
1. Gather any pending events with EventPump::poll_event()
2a. Update state based on user input
2b. Long-running background tasks continue while updating state (such as long-running glob)
3. Render state 
4. sleep for remaining frame time.

This hopefully will remove the black screen by not blocking events and rendering.
`Mode` will no longer block event iteration with long running input gathering operations.

Inspiration from https://gameprogrammingpatterns.com/game-loop.html

2019-06-25 19:56 UTC, Davejkane commented
Sounds like a solid idea to me

2019-07-02 10:53 UTC, Davejkane commented
@gurgalex, any movement on this?

2019-07-02 13:36 UTC, gurgalex commented
@Davejkane 
Sorry, the research project at university requires a lot of my time as of recently.
I'd estimate 1-2 weeks is when I'll be available again.

2019-07-03 07:02 UTC, Davejkane commented
@gurgalex, no problem, thanks for update. Best of luck with your research project.

2024-11-28 10:59 UTC, closed without merging

2024-11-28 11:00 UTC, Davejkane commented
Coming back to this project after many years away. I think we'd do this completely differently now with Async rust anyway